spring:
  application:
    name: olp
  flyway:
    enabled: true
    default-schema: OLP

  data:
    mongodb:
      host: localhost
      port: 27017
      database: products
      username: root
      password: root

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      url: redis://localhost:6379
      username: root
      password: root

server:
  port: 8080
  error:
    include-message: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html